### ISSUE TITLE
BUG: WIDGET echoing extra space in anchor tag

### ISSUE THREAD

**Issue by dkcreatto** [elementous/color-filters-for-woocommerce#1]
**Issue**: Widget is echoing extra whitespace in href attribute of A tag thus creating havoc when additional parameters are passed as GET string. e.g url turns to "[http://your_wordpress_base_url/product-color/blue/%20?additional_param=param_value](url)". That **"%20"** is there because of extra white space in widgets.php

There is an extra space after php closing tag "?>" and before attribute ending double-quotes in color-filters/includes/widgets.php line 69, 73, 88, 94.

**Example:** _**line 69**_  `<div class="rcorners" <?php echo $style; ?>><a href="<?php echo esc_url( get_term_link( $term ) ); ?> "><!-- --></a></div>`

**_Solution: remove extra space from all these four locations_**

**Comment by dominykasgel** [comment]
Thanks for reporting this @dkcreatto! We'll push your fix and add your credentials to changelog.

**Comment by dkcreatto** [comment]
Somehow this issue is still open!! Closing it.
